# Generated by Django 4.1 on 2024-01-16 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_id', models.CharField(max_length=50, unique=True)),
                ('system_guid', models.CharField(max_length=80, unique=True)),
                ('unit', models.CharField(max_length=10, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='dashboard.plant')),
            ],
        ),
        migrations.CreateModel(
            name='UnitData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quality', models.CharField(max_length=20)),
                ('derived_quality', models.CharField(max_length=20)),
                ('sample_time', models.DateTimeField()),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_data', to='dashboard.unit')),
            ],
        ),
    ]
