# Generated by Django 3.2.12 on 2024-01-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='system_guid',
            field=models.CharField(max_length=80),
        ),
    ]
