# Generated by Django 3.2.12 on 2024-01-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_unit_system_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('plant', 'unit')},
        ),
    ]
