# Generated by Django 4.1 on 2024-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240120_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='max_rated_power',
            field=models.IntegerField(default=330, verbose_name='Max Rated Power'),
        ),
    ]
