# Generated by Django 3.2.12 on 2024-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20240120_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='max_voltage',
            field=models.IntegerField(default=330),
        ),
    ]
